# Generated by Django 3.1.4 on 2021-01-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210110_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_default_news',
            field=models.CharField(choices=[('Статья', 'Статья'), ('Новость', 'Новость')], default='Новость', max_length=7, verbose_name='Новость или статья'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='categories', through='news.PostCategory', to='news.Category', verbose_name='Тэг'),
        ),
    ]
